<h3>Forums</h3>

<ol class="breadcrumb">
  <li class="active"><?php echo $this->translate("Forum List"); ?></li>
</ol>

<table class="table table-hover">

    <thead>
    <tr>
        <th>Forums</th>
        <th>Topics</th>
        <th>Posts</th>
        <th>Last Post</th>
    </tr>
    </thead>

    <tbody>
    <?php foreach($tags as $tag): ?>
    <tr onclick="location.href='<?php echo $this->url('Zf2Forum', array(
        'tagslug' => $tag->getSlug(),
        'tagid' => $tag->getTagId()
    ));?>'" onmouseover="this.style.cursor='pointer'" onmouseout="this.style.cursor='hand'">
        <td>
            <?php echo $tag->getName() . "<br />" . $tag->getDescription(); ?>
        </td>
        <td>
            <span><?php echo $tag->getThreadCount(); ?></span>
        </td>
        <td>
            <span><?php echo $tag->getMessageCount(); ?></span>
        </td>
        <td>
            <small><?php echo $this->dateFormat(
    $tag->getLastPost(),
    IntlDateFormatter::MEDIUM, // date
    IntlDateFormatter::MEDIUM, // time
    "nl_NL"
); ?></small>
        </td>
    </tr>
    <?php endforeach; ?>
    </tbody>
    
</table>
  