<h3><?php echo $this->translate("Forums"); ?></h3>

<ol class="breadcrumb">
  <li class="active"><?php echo $this->translate("Forum List"); ?></li>
</ol>

<table class="table table-hover">

    <thead>
    <tr>
        <th><?php echo $this->translate("Forums"); ?></th>
        <th><?php echo $this->translate("Topics"); ?></th>
        <th><?php echo $this->translate("Posts"); ?></th>
        <th><?php echo $this->translate("Last Post"); ?></th>
    </tr>
    </thead>

    <tbody>
    <?php foreach($tags as $tag): ?>
    <tr onclick="location.href='<?php echo $this->url('Zf2Forum', array(
        'tagslug' => $tag->getSlug(),
        'tagid' => $tag->getTagId()
    ));?>'" onmouseover="this.style.cursor='pointer'" onmouseout="this.style.cursor='hand'">
        <td>
            <?php echo $tag->getName() . "<br />" . $tag->getDescription(); ?>
        </td>
        <td>
            <span><?php echo $tag->getThreadCount(); ?></span>
        </td>
        <td>
            <span><?php echo $tag->getMessageCount(); ?></span>
        </td>
        <td>
            <small><?php echo $this->privateSmartTime()->fromDateTime($this->dateFormat(
    $tag->getLastPost(),
    IntlDateFormatter::MEDIUM, // date
    IntlDateFormatter::MEDIUM, // time
    "nl_NL"
)); ?></small>
        </td>
    </tr>
    <?php endforeach; ?>
    </tbody>
    
</table>
  