<h3><?php echo $thread->getTitle(); ?></h3>

<ol class="breadcrumb">
  <li><a href="<?php echo $this->url('forum'); ?>">Forum List</a></li>
  <li><a href="<?php // echo $this->url('Zf2Forum', array(
      //'tagslug' => $tag->getSlug(),
      //'tagid' => $tag->getTagId()
  //)); ?>"><?php // echo $tag->getName(); ?></a></li>
  <li class="active"><?php echo $thread->getTitle(); ?></li>
</ol>

<?php foreach ($messages as $message): ?>
<div class="panel panel-default">
    <div class="panel-heading clearfix">
        <h4 class="pull-left"><?php echo $message->getTitle() . " " . $this->translate("by") . " " . $message->user;?></h4>
        <small class="text-muted pull-right">
<?php
echo $this->privateSmartTime()->fromDateTime(
        $this->dateFormat(
        $message->getTimestampCreated(),
        \IntlDateFormatter::MEDIUM, // date
        \IntlDateFormatter::MEDIUM, // time
        "nl_NL"
    )
);
?></small>
    </div>
    <div class="panel-body">
        <p><?php echo $message->getText(); ?></p>
    </div>
</div>
<?php endforeach;

if ($this->showQuickReply === true) {
?>

<div class="panel panel-primary">
    <div class="panel-heading clearfix">
        <h4 class="pull-left"><?php echo $this->translate("New Message");?></h4>
    </div>
    <div class="panel-body">
        <?php
            $form = $this->form;
            $form->prepare();
            $form->setAttribute('action', $this->url('forum/topic/reply', array(
              'topicid'   => $this->thread->getId(),
              'action'     => 'newmessage')));
          $form->setAttribute('method', 'post');
          echo $this->renderForm($form);
        ?>
    </div>
</div>
<?php
}
?>
<a href="<?php //echo $this->url('Zf2Forum/thread/newmessage', array(
              //'tagslug'    => $this->tag->getSlug(),
              //'tagid'      => $this->tag->getTagId(),
              //'threadslug' => $this->thread->getSlug(),
              //'threadid'   => $this->thread->getThreadId()
              //)); ?>"><?php echo $this->translate("Reply") ;?></a>
