<?php
if(!$this->zfcUserIdentity()):
    // display the login form
    echo $this->zfcUserLoginWidget(array('redirect'=>'application'));
else:
?>
<h3><?php echo $this->translate('New Message'); ?></h3>

<?php
    $form = $this->form;
    $form->prepare();
	$form->setAttribute('action', $this->url('Zf2Forum/thread/newmessage', array(
	    'tagslug'    => $this->tag->getSlug(),
	    'tagid'      => $this->tag->getTagId(),
	    'threadslug' => $this->thread->getSlug(),
	    'threadid'   => $this->thread->getThreadId(),
	)));
	$form->setAttribute('method', 'post');
	echo $this->renderForm($form);

endif;
