<?php
if (!$this->zfcUserIdentity()) :
    // display the login form
    echo $this->zfcUserLoginWidget(array('redirect'=>'application'));
else :
?>

<h3><?php echo $this->translate('New Thread'); ?></h3>

<ol class="breadcrumb">
  <li><a href="<?php echo $this->url('forum'); ?>"><?php echo $this->translate("Forum List");?></a></li>
  <li><a href="<?php echo $this->url('forum/category', array(
      'categoryid'    => $this->category->getId(),
  )); ?>"><?php echo $category->getName(); ?></a></li>
  <li class="active"><?php echo $this->translate('New Thread'); ?></li>
</ol>

<div class="panel panel-primary">
    <div class="panel-heading clearfix">
        <h4 class="pull-left"><?php echo $this->translate('New Thread'); ?></h4>
    </div>
    <div class="panel-body">
        <?php
        $form = $this->form;
        $form->prepare();
        $form->setAttribute(
            'action',
            $this->url(
                'forum/category/newthread',
                array(
                  'categoryid'    => $this->category->getId(),
                )
            )
        );
        $form->setAttribute('method', 'post');
        echo $this->renderForm($form);
        ?>
    </div>
</div>
<?php
endif;
