<h3><?php echo $tag->getName()?></h3>

<ol class="breadcrumb">
  <li><a href="<?php echo $this->url('forum'); ?>"><?php echo $this->translate("Forum List"); ?></a></li>
  <li class="active"><?php echo $tag->getName(); ?></li>
</ol>

<a href="<?php echo $this->url('Zf2Forum/newthread', array(
                'tagslug' => $tag->getSlug(),
                'tagid' => $tag->getTagId()
            )); ?>"><?php echo $this->translate("New thread") ?></a>

<table class="table table-hover">

    <thead>
    <tr>
        <th><?php echo $this->translate("Threads"); ?></th>
        <th><?php echo $this->translate("Views"); ?></th>
        <th><?php echo $this->translate("Posts"); ?></th>
        <th><?php echo $this->translate("Last Post"); ?></th>
    </tr>
    </thead>

    <tbody>
    <?php foreach ($threads as $thread): ?>
    <tr onclick="location.href='<?php echo $this->url('Zf2Forum/thread', array(
                'tagslug' => $tag->getSlug(),
                'tagid' => $tag->getTagId(),
                'threadslug' => $thread->getSlug(),
                'threadid' => $thread->getThreadId()
            )); ?>'" onmouseover="this.style.cursor='pointer'" onmouseout="this.style.cursor='hand'">
        <td>
            <?php echo $thread->getSubject(); ?>
        </td>
        <td>
            <span><?php echo $thread->getVisitCount(); ?></span>
        </td>
        <td>
            <span><?php echo $thread->getMessageCount(); ?></span>
        </td>
        <td>
            <small><?php echo $this->privateSmartTime()->fromDateTime($this->dateFormat(
    $thread->getLastPost(),
    IntlDateFormatter::MEDIUM, // date
    IntlDateFormatter::MEDIUM, // time
    "nl_NL"
)); ?></small>
        </td>
    </tr>
    <?php endforeach; ?>
    </tbody>
    
</table>