<h3><?php echo $tag->getName()?></h3>

<ol class="breadcrumb">
  <li><a href="<?php echo $this->url('forum'); ?>"><?php echo $this->translate("Forum List"); ?></a></li>
  <li class="active"><?php echo $tag->getName(); ?></li>
</ol>

<?php
if ($this->zfcUserIdentity()) :
?>
<a href="<?php echo $this->url('forum/category/newthread', array(
                'categoryid' => $tag->getId()
            )); ?>"><?php echo $this->translate("New thread") ?></a>
<?php
endif
?>

<table class="table table-hover">
    <thead>
    <tr>
        <th><?php echo $this->translate("Threads"); ?></th>
        <th><?php echo $this->translate("Views"); ?></th>
        <th><?php echo $this->translate("Posts"); ?></th>
        <th><?php echo $this->translate("Last Post"); ?></th>
    </tr>
    </thead>

    <tbody>
    <?php foreach ($threads as $thread) : ?>
    <tr onclick="location.href='<?php echo $this->url('forum/topic', array(
                'topicid' => $thread->getId(),
            )); ?>'" onmouseover="this.style.cursor='pointer'" onmouseout="this.style.cursor='hand'">
        <td>
            <?php echo $thread->getTitle(); ?>
        </td>
        <td>
            <span><?php echo $thread->getVisitCount(); ?></span>
        </td>
        <td>
            <span><?php echo $thread->getMessageCount(); ?></span>
        </td>
        <td>
            <small><?php echo $this->privateSmartTime()->fromDateTime($this->dateFormat(
                $thread->getLastPost(),
                \IntlDateFormatter::MEDIUM, // date
                \IntlDateFormatter::MEDIUM, // time
                "nl_NL"
            )); ?></small>
        </td>
    </tr>
    <?php endforeach; ?>
    </tbody>

</table>